version: '3'

services:
  db:
    container_name: ${APP_NAME}-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  adminer:
    container_name: ${APP_NAME}-adminer
    image: adminer
    restart: always
    ports:
      - 9081:8080

  api:
    container_name: ${APP_NAME}-api
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_SERVER: ${MYSQL_SERVER}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - 9080:8080