version: '3'

services:
  api:
    container_name: ${APP_NAME}-api
    image: springboot-docker-compose-app:1
    build:
      context: ./docker/java
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "9080:8080"