spring.datasource.url=jdbc:mysql://127.0.0.1:3306/library_db?serverTimezone=UTC
spring.datasource.username=allan
spring.datasource.password=dev

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update

#spring.flyway.url=jdbc:mysql://127.0.0.1:3306/library_db?serverTimezone=UTC
#spring.flyway.schemas=library_db
#spring.flyway.user=allan
#spring.flyway.password=dev