spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:library_db}?serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect